Improve home page UI.
MakeContributions/markdown-dungeon pull request #144
Opened 2021-03-27 21:17 UTC by gauravsingh5

Made the UI page a little better.

2021-03-28 07:25 UTC, gauravsingh5 commented
Site isn't responsive on Netlify, but when I run it locally it is.

2021-03-28 16:16 UTC, gauravsingh5 commented
I don't know why this is happening but whenever I open it in mobile view it doesn't render correctly until I click on a card and then go back to the home page.

2021-03-28 16:28 UTC, gauravsingh5 commented
It's changing after building. So it's not a Netlify problem

2021-03-28 16:37 UTC, gauravsingh5 commented
I overthought it. It was really simple. I didn't even need react-device-detect.

2021-03-30 11:41 UTC, ming-tsai commented
Hi @gauravsingh5,
Thanks for contributions, could your replace double quotes to single?
I should configure prettier

2021-04-01 14:25 UTC, ming-tsai commented
Hi @gauravsingh5,
Please ensure the card is the same size and the ArrowForward button should on left side
![image](https://user-images.githubusercontent.com/37890026/113308526-413a6480-92d4-11eb-816e-c8333ed0df22.png)

2021-04-01 15:09 UTC, ming-tsai requested changes
Sorry, and rollback the change of hiding navbar, when has a lot of dungeons, or in the future, we will use it

2021-04-01 15:14 UTC, ming-tsai requested changes

2021-04-01 15:14 UTC, ming-tsai commented on src/pages/404.jsx
> +import Layout from '../components/layout';
Rollback this change, I didn't see any change

2021-04-01 15:14 UTC, ming-tsai commented on src/utils/styles.js
> -import { makeStyles } from '@material-ui/core/styles';
Replace all double quotes to single quote on this file

2021-04-01 15:14 UTC, ming-tsai commented on src/pages/index.jsx
> +          </Container>
Pleas fix the ident of these nodes

2021-04-01 16:31 UTC, gauravsingh5 commented
The size of the cards didn't match because the description of the Chinese dungeon was 3 characters less. I used google translate and added "and start" to the description but you can change it as i don't know Chinese. Just add 3 more characters to the description.

2021-04-01 16:31 UTC, ming-tsai requested changes

2021-04-01 16:31 UTC, ming-tsai commented on chinese/great-wall/begin-journey.md
> +你現在是一個小小兵，請不要選錯否則會被你的將軍砍頭或回家吃自己开始。
Why do you change this phrase?

2021-04-01 16:32 UTC, ming-tsai commented
> The size of the cards didn't match because the description of the Chinese dungeon was 3 characters less. I used google translate and added "and start" to the description but you can change it as i don't know Chinese. Just add 3 more characters to the description.

Couldn't add the same size for the card o material ui?

2021-04-01 16:36 UTC, gauravsingh5 commented
I don't know about material ui much but let me try.

2021-04-01 16:39 UTC, ming-tsai commented
Could you tell me what do you want to change?
Because for me the old card size is good, it doesn't seem too big or too small

2021-04-01 16:41 UTC, gauravsingh5 commented
All the cards were located in center and the space on the side was looking weird.

2021-04-01 16:43 UTC, ming-tsai commented
For me is good, I'm just think have a background image 
![image](https://user-images.githubusercontent.com/37890026/113326545-cf6c1600-92e7-11eb-9c0d-72a9575ea81e.png)

2021-04-01 16:43 UTC, gauravsingh5 commented
Should we have 4 per row?

2021-04-01 16:45 UTC, ming-tsai commented
We could try, but keep it the same size

2021-04-01 16:46 UTC, gauravsingh5 commented
Ok

2021-04-01 16:50 UTC, gauravsingh5 commented
![image](https://user-images.githubusercontent.com/65955464/113327280-619c0a80-9338-11eb-949b-247f9223d8c6.png)

2021-04-01 16:51 UTC, gauravsingh5 commented
Do you know how to size it?

2021-04-01 16:55 UTC, gauravsingh5 commented
![image](https://user-images.githubusercontent.com/65955464/113327844-0e768780-9339-11eb-8d07-fe6a767b0439.png)
I just sliced the excerpt

2021-04-01 16:56 UTC, gauravsingh5 commented
Maybe we can add 3 dots at the end.

2021-04-01 16:58 UTC, ming-tsai commented
For me is good

2021-04-01 16:59 UTC, ming-tsai commented on src/components/card-grid.jsx
> +            <Typography>{post.excerpt.slice(0, 65)}</Typography>
Why just 65 characters?

2021-04-01 17:00 UTC, gauravsingh5 commented
It seemed to work

2021-04-01 17:00 UTC, gauravsingh5 commented
This is a temporary fix btw, we need to find a permanent one

2021-04-01 17:01 UTC, ming-tsai commented on src/components/card-grid.jsx
> +            <Typography>{post.excerpt.slice(0, 65)}</Typography>
If you just want 65 characters, you could use the gatsby graphql query, on the `pruneLength` change to 65
 ![image](https://user-images.githubusercontent.com/37890026/113328418-41455f00-92ea-11eb-83e8-cd4efd044598.png)

2021-04-01 17:02 UTC, ming-tsai commented
It fails because you change the text alignment to the center?

2021-04-01 17:03 UTC, gauravsingh5 commented
It's the number of lines it takes

2021-04-01 17:04 UTC, gauravsingh5 commented
![image](https://user-images.githubusercontent.com/65955464/113328767-5fd34680-933a-11eb-8435-26149332645b.png)
This is right align

2021-04-01 17:04 UTC, gauravsingh5 commented
It's without the slice btw.

2021-04-01 17:05 UTC, ming-tsai commented
> ![image](https://user-images.githubusercontent.com/65955464/113328767-5fd34680-933a-11eb-8435-26149332645b.png)
> This is right align

You could specify the `pruneLength` to another length
![image](https://user-images.githubusercontent.com/37890026/113328917-e6603780-92ea-11eb-92f7-0bba8c6fe318.png)

2021-04-01 17:06 UTC, ming-tsai commented
But the question, why the current is align?
![image](https://user-images.githubusercontent.com/37890026/113329027-0db70480-92eb-11eb-9aaa-fc91598c8e51.png)

2021-04-01 17:07 UTC, gauravsingh5 commented
![image](https://user-images.githubusercontent.com/65955464/113329122-d2442680-933a-11eb-8d03-4732a39dff85.png)
Prune 30 in English vs Chinese

2021-04-01 17:09 UTC, gauravsingh5 commented
![image](https://user-images.githubusercontent.com/65955464/113329314-091a3c80-933b-11eb-9f93-892a0644ac0f.png)
This is Prune 10

2021-04-01 17:09 UTC, gauravsingh5 commented
I guess prune 10 should work.

2021-04-01 17:09 UTC, ming-tsai commented
I will check your branch

2021-04-01 17:14 UTC, gauravsingh5 commented
Just check the [deploy preview](https://deploy-preview-144--markdown-dungeon.netlify.app)

2021-04-01 17:14 UTC, ming-tsai commented
The 10 prune didn't show the description of dungeon

2021-04-01 17:16 UTC, gauravsingh5 commented
We can leave it like a teaser, if they click on it they see the full description.

2021-04-01 17:19 UTC, ming-tsai commented
Let me check what is going with the card

2021-04-01 18:51 UTC, ming-tsai commented
Hi @gauravsingh5,
Could you set the prune length to 100? I will check when merge to master

2021-04-01 19:02 UTC, ming-tsai approved these changes
Nice work 🎉🙌🙌🙌

2021-04-01 19:03 UTC, merged