I changed the visual look, added emojis, and edited grammar.
MakeContributions/markdown-dungeon pull request #159
Opened 2021-06-01 10:47 UTC by NoorinSakhi

Please take a look at my changes and see if you approve thank you.

2021-06-04 00:52 UTC, ming-tsai commented on english/covid-19/0/0-C.md
> +- [ ] [🚪 Find a way out](../WIP.md)
Please remove `[ ]`
```suggestion
- [🚪 Find a way out](../WIP.md)
```

2021-06-04 00:55 UTC, ming-tsai requested changes
Hi @NoorinSakhi,
Everything is good, but please remove all `[ ]` to all files

2021-06-04 09:37 UTC, NoorinSakhi commented
I removed all the ```[]```. Thank you.

2021-06-04 14:30 UTC, ming-tsai requested changes
Hi @NoorinSakhi,
Sorry I didn't see you are converting the text to tile, and it doesn't look very well, so my recommendation `add the emojis and edited the grammar`

2021-06-06 12:52 UTC, ming-tsai approved these changes
Hi @NoorinSakhi,
Nice work

2021-06-06 12:52 UTC, merged