I have added color, emojis and changed the text style
MakeContributions/markdown-dungeon pull request #161
Opened 2021-06-04 11:32 UTC by HareerSakhi

2021-06-04 14:31 UTC, ming-tsai requested changes
Hi @HareerSakhi,
Please do not change the text to the title, only add the emoji or color

2021-06-04 15:02 UTC, HareerSakhi commented
I have removed all of the text size changes. Thanks

2021-06-04 15:07 UTC, ming-tsai requested changes

2021-06-04 15:07 UTC, ming-tsai commented on english/normal-dungeon/4/4.md
> + You open the door 🚪 to your neighbour's house 🏡, and the first thing you see is a <span style= "color:red">trail of blood💉 streaked on the floor...</span>
DO NOT use HTML code on the markdown file. if you are more advanced and know ReactJs you could beautify the page

2021-06-05 12:02 UTC, HareerSakhi commented
I have gotten rid of the inline HTML, and made the page more visible by spacing out the text a little bit, added more emojis, and fixed some typos and grammar errors that I spotted. Thanks

2021-06-05 12:38 UTC, HareerSakhi commented
I have gotten rid of the inline HTML, and made the page more visible by spacing out the text a little bit to make the writing more visible, added more emojis, and fixed some typos and grammar errors that I spotted. Thanks.

2021-06-06 10:54 UTC, HareerSakhi commented
I have also completed folder 5 of the english normal-dungeon, adding more emojis (and also adding spaces before them), fixing grammatical errors, fixed one or two of the sentences so that they make more sense, and spacing text out.

2021-06-06 12:58 UTC, ming-tsai approved these changes
Hi @HareerSakhi,
Nice work, and welcome to be part of the team.
> The invitation [link](https://github.com/MakeContributions)

2021-06-06 12:58 UTC, merged