Added time-travel dungeon
MakeContributions/markdown-dungeon pull request #165
Opened 2021-06-22 17:52 UTC by hkumar0132

2021-06-22 18:14 UTC, ming-tsai requested changes

2021-06-22 18:14 UTC, ming-tsai commented on english/time-travel/1/0.md
> +
Delete these lines

2021-06-22 18:21 UTC, hkumar0132 commented on english/time-travel/1/0.md
> +
Done.

2021-06-22 19:43 UTC, ming-tsai approved these changes

2021-06-22 19:45 UTC, ming-tsai requested changes
Hi @hkumar0132,
Could you add your dungeon on this [options](https://github.com/hkumar0132/markdown-dungeon/blob/add-dungeon/start-new-game.md)

2021-06-22 22:01 UTC, ming-tsai commented on src/pages/index.jsx
> +            })}
Rollback this change and `package-lock.json`

2021-06-24 05:49 UTC, hkumar0132 commented
Hey @ming-tsai I have made the changes. Let me know if any more changes required.

2021-06-24 12:22 UTC, ming-tsai approved these changes
Nice work @hkumar0132 🎉🚀🥇

2021-06-24 12:23 UTC, merged