Expand room in Covid-19 Dungeon
MakeContributions/markdown-dungeon pull request #225
Opened 2022-08-07 04:03 UTC by TJXKON

Expanded the option of room 1-D in Covid-19 Dungeon.
This is my first time contributing a project, hope to let me know if it is ok.

2022-08-08 12:05 UTC, Arsenic-ATG requested changes
some minor typo fix and rephrasing

2022-08-08 12:05 UTC, Arsenic-ATG commented on english/covid-19/1/1-DAA.md
> +**Is it worth?**
```suggestion
**was it worth the risk?**
```

2022-08-08 12:05 UTC, Arsenic-ATG commented on english/covid-19/1/1-DAB.md
> +You have been tested positive of Covid-19 😷.
```suggestion
You have been tested COVID-19 positive😷.
```

2022-08-08 12:05 UTC, Arsenic-ATG commented on english/covid-19/1/1-DA.md
> +Your coughed and felt not well 🤒.
```suggestion
You coughed and felt unwell 🤒.
```

2022-08-28 21:21 UTC, ming-tsai commented
Hi @TJXKON,
Could you please fix this spelling problems?
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/37890026/187094993-f73318db-0ef1-405d-97ab-547e6cf87161.png">

2022-08-29 02:59 UTC, Arsenic-ATG commented
Previous suggested changes were marked resolved by author but I can neither see a commit implementing those changes nor a reasoning for marking those as resolved, thus marking them unresolved again.

2022-10-06 17:46 UTC, closed without merging